In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [151]:
def gen_Y(pi_0):
	# H_0 : Y ~ [N(3, 1) N(-1, 1)]
	# H_1 : Y_1, Y_2 ~ P_x; p(x) = 1/2*exp(-|x|)
    N = int(500)
    Y = np.zeros((2, N))
    ber_exp = np.random.binomial(n=1, p=1-pi_0, size=N)
    for i in ber_exp:
        if i == 0:
            Y[:, i] = h0()
        else:   
            Y[:, i] = h1()
    #Y = np.array(Y)#.reshape(2, -1)
    return Y
	
def px(instances=1):
    return np.random.laplace(size=instances)
# 	X = np.random.uniform(size=(instances,1))
# 	Y = np.random.uniform(size=(instances,1))
# 	return np.log(X/Y)

def h0():
    return np.array([np.random.normal(3, 1), np.random.normal(-1, 1)]).reshape(2, )

def h1():
    return np.array([px(), px()]).reshape(2, )

def opt_decision_rule(pi_0, Y):
    tau = pi_0/(1 - pi_0)
    a = np.array([3, -1]).reshape(2, 1)
    #decision = (np.linalg.norm(Y, axis=0)**2) + a@Y - 2*np.linalg.norm(Y, axis=0) <= 2*np.log(2*tau/np.pi) -10
    decision = (np.pi/2)*np.exp(0.5*(np.linalg.norm(Y - a, axis=0)**2) - np.linalg.norm(Y, axis=0, ord=1)) >= tau
    return decision.reshape(-1, )

def p0G1(delta, Y):
    G1 = Y[:, delta]
    a = np.array([3, -1]).reshape(2, 1)
    p0G1 = (0.5/np.pi)*np.exp(-0.5*(np.linalg.norm(G1-a, axis=0)**2))
    print(p0G1)
    return np.sum(p0G1)

def p1G0(delta, Y):
    G0 = Y[:, np.logical_not(delta)]
    p1G0 = 0.25*np.exp(-1*(np.linalg.norm(G0, axis=0, ord=1)))
    return np.sum(p1G0)

def V(pi_0, Y):
    delta = opt_decision_rule(pi_0, Y)
    return pi_0*p0G1(delta, Y) + (1-pi_0)*p1G0(delta, Y)

#print(Y)

In [152]:
x = np.array([[3, 5], [4, 12]])
print(x)
print(np.linalg.norm(x, axis=0))

[[ 3  5]
 [ 4 12]]
[ 5. 13.]


In [182]:
pi_0 = 0.2
Y = gen_Y(pi_0)

print(V(pi_0, Y))

0.11265606790663868


In [150]:
# y = np.array([[0, 0], [0, 6]])
# pi_0 = 0.5
# d = opt_decision_rule(pi_0, y).reshape(-1, )
# print(d)
# print(np.logical_not(d))
# y = y[:, d]
# print(y)
# # a = np.array([-3, 1]).reshape(2, 1)
# # print(np.linalg.norm(y-a, axis=0))
# print(p0G1(y, d))
# print(p1G0(y, d))
pi_0 = 0.5
Y = np.array([[3, 0], [-1, 0]])
print(p1G0(pi_0, Y))

[0.00457891 0.25      ]
(2,)
0.25457890972218356


In [172]:
Y = np.array([[3, 0], [-1, 0]])
print(opt_decision_rule(0.1, Y))

[False  True]


In [177]:
x = np.array([[1, 3, 4, 6], [2, 45, 6, 7]])
#[False, True]
print(x)
delta = np.array([True, False, False, True])
Gamma1 = x[:, np.logical_not(delta)]
print(Gamma1)

[[ 1  3  4  6]
 [ 2 45  6  7]]
[[ 3  4]
 [45  6]]
